'use client'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from '@/components/app.header'
import { Container} from 'react-bootstrap';
import AppFooter from '@/components/app.footer';
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <Container>{children}</Container>
        <AppFooter/>
        <ToastContainer
          position="bottom-center"
          autoClose={1000}
          closeOnClick
          theme='light'

          />
      </body>
    </html>
  )
}
